USE maulik;

#QUERY 1
CREATE TABLE CUSTOMERS(
    ID INT PRIMARY KEY,
    NAME VARCHAR(15),
    AGE NUMERIC,
    ADDRESS VARCHAR(25),
    SALARY NUMERIC(8,0)
);

INSERT INTO CUSTOMERS VALUES (1,"NIDHI",38,"DELHI",2000);
INSERT INTO CUSTOMERS VALUES (2,"ANKIT",25,"MUMBAI",1500);
INSERT INTO CUSTOMERS VALUES (3,"CHETAN",31,"NOIDA",2000);
INSERT INTO CUSTOMERS VALUES (4,"HARDIK",22,"MP",6500);
INSERT INTO CUSTOMERS VALUES (5,"KOMAL",23,"BHOPAL",8500);
INSERT INTO CUSTOMERS VALUES (6,"MUFFY",27,"KOTA",4500);
INSERT INTO CUSTOMERS VALUES (7,"KAUSHIK",21,"INDORE",10000);   

#QUERY 2
 SELECT MIN(AGE), MAX(AGE) FROM CUSTOMERS;

#QUERY 3
SELECT COUNT(AGE) FROM CUSTOMERS;

#QUERY 4
SELECT AVG(AGE) FROM CUSTOMERS;

#QUERY 5
SELECT SUM(SALARY) FROM CUSTOMERS;

#QUERY 6
SELECT NAME FROM CUSTOMERS 
WHERE NAME LIKE "C%N";

#QUERY 7
SELECT NAME FROM CUSTOMERS 
WHERE NAME LIKE "_A%";

#QUERY 8
SELECT * FROM CUSTOMERS 
WHERE ADDRESS = "DELHI" OR 
ADDRESS = "BHOPAL" OR ADDRESS = "MP";

#QUERY 9
SELECT * FROM CUSTOMERS 
WHERE ADDRESS != "DELHI" AND 
ADDRESS != "BHOPAL" AND ADDRESS != "MP"; 

#QUERY 10
SELECT * FROM CUSTOMERS 
WHERE AGE >= 25 AND AGE <= 30;

#QUERY 11
SELECT * FROM CUSTOMERS 
WHERE AGE < 25 OR AGE >= 30;

#QUERY 12
SELECT * FROM CUSTOMERS 
ORDER BY NAME;

#QUERY 13
SELECT * FROM CUSTOMERS 
ORDER BY NAME DESC;

#QUERY 14
SELECT NAME AS CUSTNAME 
FROM CUSTOMERS;

#QUERY 15
SELECT DISTINCT(SALARY) 
FROM CUSTOMERS;

#QUERY 16
SELECT SALARY * 2 AS DOUBLE_SALARY 
FROM CUSTOMERS;

#QUERY 17
CREATE TABLE NEW_SALARY AS 
SELECT ID,NAME,AGE,ADDRESS,
SALARY * 2 AS SALARY FROM CUSTOMERS;

#QUERY 18
ALTER TABLE NEW_SALARY
ADD PRIMARY KEY(ID);

#QUERY 19
ALTER TABLE NEW_SALARY
DROP PRIMARY KEY;

#QUERY 20
ALTER TABLE NEW_SALARY
ADD UNIQUE(ID);

#QUERY 21
UPDATE CUSTOMERS
SET ADDRESS = "MUMBAI" WHERE ID = 1;

#QUERY 22
ALTER TABLE CUSTOMERS
ADD CHECK(AGE >= 18);

#QUERY 23
INSERT INTO CUSTOMERS VALUES (8,"NITIN",34,"DELHI",2000);
INSERT INTO CUSTOMERS VALUES (9,"ANIKET",25,"MUMBAI",1500);
INSERT INTO CUSTOMERS VALUES (10,"CHINTAN",31,"NOIDA",2000);
INSERT INTO CUSTOMERS VALUES (11,"HARDIKA",19,"MP",6500);

#QUERY 24
SELECT SUM(SALARY) FROM CUSTOMERS 
WHERE ADDRESS = "MP";

#QUERY 25
CREATE TABLE ORDERS(
    ORDER_ID INT PRIMARY KEY,
    CUST_ID INT,
    ORDER_DATE DATE,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(ID)
);

DROP TABLE CUSTOMERS;
DROP TABLE ORDERS;